export const data = [
  { title: "  كود الاعلان", content: "#253698" },
  { title: "توقيت اضافة الاعلان ", content: "25 يناير 2023" },
  { title: "اسم صاحب الاعلان", content: "احمد محمد علي" },
  { title: "الدولة", content: "الكويت" },
  { title: "المنطقة", content: "الخيران" },
  { title: "نوع العقار", content: "مشاريع" },
  { title: "نوع المشروع", content: "مطعم" },
  { title: "الغرض", content: "بيع" },
  { title: "نوع الاعلان", content: "مشروع" },
  { title: "رقم الموبايل", content: "56286482" },
  { title: "رقم الواتس اب", content: "56286482" },
  { title: "السعر", content: "0 دك" },
  { title: "عدد مشاهدات الاعلان", content: "500" },
  { title: "عدد لايكات علي العقار", content: "50" },
  { title: "عدد المتصلين", content: "10" },
];
export const tableData = [
  {
    id: "01",
    ad_code: "VLZ-452",
    ad_date: "اليوم -1 دقيقه",
    country: "الكويت ",
    area: "العدان",
    estate_type: " نوع العقار",
    purpose: "ايجار",
    ad_type: "مميز",
    price: "0.0 دك ",
    status: "نشط",
  },
  {
    id: "01",
    ad_code: "VLZ-452",
    ad_date: "اليوم -1 دقيقه",
    country: "الكويت ",
    area: "العدان",
    estate_type: " نوع العقار",
    purpose: "ايجار",
    ad_type: "مميز",
    price: "0.0 دك ",
    status: "محظور",
  },
  {
    id: "01",
    ad_code: "VLZ-452",
    ad_date: "اليوم -1 دقيقه",
    country: "الكويت ",
    area: "العدان",
    estate_type: " نوع العقار",
    purpose: "ايجار",
    ad_type: "مميز",
    price: "0.0 دك ",
    status: "نشط",
  },
  {
    id: "01",
    ad_code: "VLZ-452",
    ad_date: "اليوم -1 دقيقه",
    country: "الكويت ",
    area: "العدان",
    estate_type: " نوع العقار",
    purpose: "ايجار",
    ad_type: "مميز",
    price: "0.0 دك ",
    status: "محظور",
  },
  {
    id: "01",
    ad_code: "VLZ-452",
    ad_date: "اليوم -1 دقيقه",
    country: "الكويت ",
    area: "العدان",
    estate_type: " نوع العقار",
    purpose: "ايجار",
    ad_type: "مميز",
    price: "0.0 دك ",
    status: "نشط",
  },
  {
    id: "01",
    ad_code: "VLZ-452",
    ad_date: "اليوم -1 دقيقه",
    country: "الكويت ",
    area: "العدان",
    estate_type: " نوع العقار",
    purpose: "ايجار",
    ad_type: "مميز",
    price: "0.0 دك ",
    status: "محظور",
  },
  {
    id: "01",
    ad_code: "VLZ-452",
    ad_date: "اليوم -1 دقيقه",
    country: "الكويت ",
    area: "العدان",
    estate_type: " نوع العقار",
    purpose: "ايجار",
    ad_type: "مميز",
    price: "0.0 دك ",
    status: "نشط",
  },
  {
    id: "01",
    ad_code: "VLZ-452",
    ad_date: "اليوم -1 دقيقه",
    country: "الكويت ",
    area: "العدان",
    estate_type: " نوع العقار",
    purpose: "ايجار",
    ad_type: "مميز",
    price: "0.0 دك ",
    status: "محظور",
  },
  {
    id: "01",
    ad_code: "VLZ-452",
    ad_date: "اليوم -1 دقيقه",
    country: "الكويت ",
    area: "العدان",
    estate_type: " نوع العقار",
    purpose: "ايجار",
    ad_type: "مميز",
    price: "0.0 دك ",
    status: "نشط",
  },
  {
    id: "01",
    ad_code: "VLZ-452",
    ad_date: "اليوم -1 دقيقه",
    country: "الكويت ",
    area: "العدان",
    estate_type: " نوع العقار",
    purpose: "ايجار",
    ad_type: "مميز",
    price: "0.0 دك ",
    status: "محظور",
  },
  {
    id: "01",
    ad_code: "VLZ-452",
    ad_date: "اليوم -1 دقيقه",
    country: "الكويت ",
    area: "العدان",
    estate_type: " نوع العقار",
    purpose: "ايجار",
    ad_type: "مميز",
    price: "0.0 دك ",
    status: "نشط",
  },
  {
    id: "01",
    ad_code: "VLZ-452",
    ad_date: "اليوم -1 دقيقه",
    country: "الكويت ",
    area: "العدان",
    estate_type: " نوع العقار",
    purpose: "ايجار",
    ad_type: "مميز",
    price: "0.0 دك ",
    status: "محظور",
  },
  {
    id: "01",
    ad_code: "VLZ-452",
    ad_date: "اليوم -1 دقيقه",
    country: "الكويت ",
    area: "العدان",
    estate_type: " نوع العقار",
    purpose: "ايجار",
    ad_type: "مميز",
    price: "0.0 دك ",
    status: "نشط",
  },
];
