export const data = [
  {
    id: "1",
    code: "VLZ-452",
    created_at: "اليوم -1 دقيقه",
    name: "أحمد محمد علي ",
    phone: "(480) 555-0103  ",
    balance: "0.0 ",
    status: "active",
  },
  {
    id: "1",
    code: "VLZ-452",
    created_at: "اليوم -1 دقيقه",
    name: "أحمد محمد علي ",
    phone: "(480) 555-0103  ",
    balance: "0.0 ",
    status: "inactive",
  },
  {
    id: "1",
    code: "VLZ-452",
    created_at: "اليوم -1 دقيقه",
    name: "أحمد محمد علي ",
    phone: "(480) 555-0103  ",
    balance: "0.0 ",
    status: "active",
  },
  {
    id: "1",
    code: "VLZ-452",
    created_at: "اليوم -1 دقيقه",
    name: "أحمد محمد علي ",
    phone: "(480) 555-0103  ",
    balance: "0.0 ",
    status: "inactive",
  },
];
