export const data = [
  {
    id: "1",
    client_code: "VLZ-452",
    register_date: "اليوم -1 دقيقه",
    client_name: "أحمد محمد علي ",
    phone: "(480) 555-0103  ",
    charge: "0.0 دك ",
    status: "نشط",
  },
  {
    id: "1",
    client_code: "VLZ-452",
    register_date: "اليوم -1 دقيقه",
    client_name: "أحمد محمد علي ",
    phone: "(480) 555-0103  ",
    charge: "0.0 دك ",
    status: "محظور",
  },
  {
    id: "1",
    client_code: "VLZ-452",
    register_date: "اليوم -1 دقيقه",
    client_name: "أحمد محمد علي ",
    phone: "(480) 555-0103  ",
    charge: "0.0 دك ",
    status: "نشط",
  },
  {
    id: "1",
    client_code: "VLZ-452",
    register_date: "اليوم -1 دقيقه",
    client_name: "أحمد محمد علي ",
    phone: "(480) 555-0103  ",
    charge: "0.0 دك ",
    status: "محظور",
  },
  {
    id: "1",
    client_code: "VLZ-452",
    register_date: "اليوم -1 دقيقه",
    client_name: "أحمد محمد علي ",
    phone: "(480) 555-0103  ",
    charge: "0.0 دك ",
    status: "نشط",
  },
  {
    id: "1",
    client_code: "VLZ-452",
    register_date: "اليوم -1 دقيقه",
    client_name: "أحمد محمد علي ",
    phone: "(480) 555-0103  ",
    charge: "0.0 دك ",
    status: "محظور",
  },
  {
    id: "1",
    client_code: "VLZ-452",
    register_date: "اليوم -1 دقيقه",
    client_name: "أحمد محمد علي ",
    phone: "(480) 555-0103  ",
    charge: "0.0 دك ",
    status: "نشط",
  },
  {
    id: "1",
    client_code: "VLZ-452",
    register_date: "اليوم -1 دقيقه",
    client_name: "أحمد محمد علي ",
    phone: "(480) 555-0103  ",
    charge: "0.0 دك ",
    status: "محظور",
  },
  {
    id: "1",
    client_code: "VLZ-452",
    register_date: "اليوم -1 دقيقه",
    client_name: "أحمد محمد علي ",
    phone: "(480) 555-0103  ",
    charge: "0.0 دك ",
    status: "نشط",
  },
  {
    id: "1",
    client_code: "VLZ-452",
    register_date: "اليوم -1 دقيقه",
    client_name: "أحمد محمد علي ",
    phone: "(480) 555-0103  ",
    charge: "0.0 دك ",
    status: "محظور",
  },
];
